spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cxkaquq6qa78.ap-northeast-2.rds.amazonaws.com:3306/MnM
    username: root
    password: sklookie1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true


jwt:
  header: Authorization
  security-key: YmFzZTY0IGVuY29kZWQgNTI2IGJpdCBzZWNyZXQga2V5IHRoYXQgaXMgbGFyZ2Ugc2FmZSBhbmQgdXNlZCB3aXRoIEhTNTEy

logging:
  level:
    org.springframework.security: DEBUG
    com.mnm.backend: DEBUG

