version: '3.8'

services:
  app-green:
    image: hyouzl/mnm-backend-server:server-prod-green
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=green
    networks:
      - app-network